### ISSUE TITLE
Problem with data querying using JOPA (LocalDate vs dateTime)

### ISSUE THREAD

**Issue by grigoart** [kbss-cvut/jopa#100]
When performing the following query (using JOPA):
```java
em.createNativeQuery("SELECT DISTINCT ?x WHERE {" +
			"?x cm:some_predicate ?dateValue .\n" +
			"}", getType())
	.setParameter("dateValue", LocalDate.of(2021,1,1))
	.getResultList();
```
it is internally executed as:
```sparql
SELECT DISTINCT ?x
WHERE {
	?x cm:some_predicate "2021-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
}
```
however, since JOPA persists entity objects (using `em.persist()`) with `java.time.LocalDate` properties like datetime (e.g. _"2021-01-01T00:00:00.000+01:00"^^xsd:dateTime_) I expect the query above to be executed as:
```sparql
SELECT DISTINCT ?x
WHERE {
	?x cm:some_predicate "2021-01-01T00:00:00.000+01:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
}
```
i.e. with time and zone.

---
PS: the folllowing code also does not help:
```java
em.createNativeQuery("SELECT DISTINCT ?x WHERE {" +
			"?x cm:some_predicate ?dateValue .\n" +
			"}", getType())
	.setParameter("dateValue", ZonedDateTime.of(LocalDate.of(2021,1,1), LocalTime.MIN, ZoneId.systemDefault()))
	.getResultList();
```
which is internally executed as:
```sparql
SELECT DISTINCT ?x
WHERE {
	?x cm:some_predicate "2021-01-01T00:00+01:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
}
```
_(the second and millisecond parts of the datetime are missing)_

**Comment by grigoart** [comment]
To solve the problem, I am currently using this workaround:
```java
em.createNativeQuery("SELECT DISTINCT ?x WHERE {" +
			"?x cm:some_predicate \"" + LocalDate.of(2021,1,1).toString() + "T00:00:00.000" + TimeZone.getDefault().toZoneId().getRules().getOffset(Instant.now()).getId() +
			"\"^^<http://www.w3.org/2001/XMLSchema#dateTime> .\n" +
			"}", getType())
	.getResultList();
```
that builds and appends the value manually, so i do not use parameter `?dateValue` of the specific java type (i.e. `java.time.LocalDate`):
```java
"2021-01-01T00:00:00.000+01:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>
```

**Comment by ledsoft** [comment]
@grigoart This is currently under development in #95

**Comment by ledsoft** [comment]
Please try with [0.18.0](https://github.com/kbss-cvut/jopa/releases/tag/v0.18.0)

**Comment by ledsoft** [comment]
Closing the ticket due to inactivity. Feel free to reopen if there is a problem.
