### ISSUE TITLE
Ontodriver-sesame module has conflicting dependencies

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/jopa#107]
I am getting following error,
```
java.lang.NoSuchMethodError: 'void org.eclipse.rdf4j.query.algebra.evaluation.EvaluationStrategyFactory.setTrackResultSize(boolean)'
```

while using dependency:
```
        <dependency>
            <groupId>cz.cvut.kbss.jopa</groupId>
            <artifactId>ontodriver-sesame</artifactId>
            <version>0.17.2</version>
        </dependency>
```

The problem seems to be visible in output of `mvn dependency:tree`:
![image](https://user-images.githubusercontent.com/3962237/157708564-dd20e1f1-ebb2-42ca-8aa1-bf1285c51573.png)

My workaround that works:
```
        <dependency>
            <groupId>cz.cvut.kbss.jopa</groupId>
            <artifactId>ontodriver-sesame</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.eclipse.rdf4j</groupId>
                    <artifactId>rdf4j-repository-sail</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.eclipse.rdf4j</groupId>
            <artifactId>rdf4j-repository-sail</artifactId>
            <version>3.7.3</version>
        </dependency>
```

**Comment by ledsoft** [comment]
1. This ticket concerns apparently version 0.17.2, which is outdated, so it cannot be fixed retrospectively.
2. All RDF4J dependencies are updated at the same time via a Maven property (see [pom.xml](https://github.com/kbss-cvut/jopa/blob/master/ontodriver-sesame/pom.xml)). Is it possible that your application depends on multiple RDF4J versions and this causes the conflict? I haven't seen this error in any of the systems that use JOPA, which is quite strange and makes me think it is not a JOPA issue. What is your overall dependency tree?

**Comment by ledsoft** [comment]
For example, you have RDF4J artifacts version 2.5.3 (including the conflicting one you mention above) in `dependencyManagement` in s-pipes-parent.

**Comment by blcham** [comment]
You are right. I did not realize that i could change indirect dependency through `dependencyManagement` section. After changing it there, everything works fine.
Thanks @ledsoft.
