### ISSUE TITLE
Datatype in JENA doesn't work 

### ISSUE THREAD

**Issue by Matthew-Kulich** [kbss-cvut/jopa#113]
Datatype `http://www.w3.org/ns/csvw#uriTemplate` is not specified in the output while `http://www.w3.org/2001/XMLSchema#int` works fine.

The problem can be seen in the following picture.

![image](https://user-images.githubusercontent.com/67843655/187209179-9bcfd103-dfdc-485f-9907-83f79116fa76.png)

**Comment by ledsoft** [comment]
Fixed in 0.18.7.
