### ISSUE TITLE
AspectJ warning + ClassCastException

### ISSUE THREAD

**Issue by JensPiegsa** [kbss-cvut/jopa#194]
Hi,

First of all, I want to let you know that I am really happy to have found your project. It looks really promising. In my first attempts to explore JOPA, I encountered a problem with AspectJ. I would be very happy for any possible solutions or advice.

## Steps to reproduce

I intentionally did not use the IDE here because I read that it can interfere with this issue.

### 1. pom.xml:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	...

	<properties>
		<java.min.version>17</java.min.version>
		<jopa-version>1.1.1</jopa-version>
		<aspectj.version>1.9.20</aspectj.version>

		...

	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>dev.aspectj</groupId>
				<artifactId>aspectj-maven-plugin</artifactId>
				<version>1.13.1</version>
				<configuration>
					<source>${java.min.version}</source>
					<target>${java.min.version}</target>
					<complianceLevel>${java.min.version}</complianceLevel>
					<aspectLibraries>
						<aspectLibrary>
							<groupId>cz.cvut.kbss.jopa</groupId>
							<artifactId>jopa-impl</artifactId>
						</aspectLibrary>
					</aspectLibraries>
					<outxml>true</outxml>
					<showWeaveInfo>true</showWeaveInfo>
					<verbose>true</verbose>
					<encoding>UTF-8 </encoding>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.aspectj</groupId>
						<artifactId>aspectjtools</artifactId>
						<version>${aspectj.version}</version>
					</dependency>
					<dependency>
						<groupId>org.aspectj</groupId>
						<artifactId>aspectjrt</artifactId>
						<version>${aspectj.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<phase>process-classes</phase>
						<goals>
							<goal>compile</goal>
							<goal>test-compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>

		...

	</build>

	<dependencies>
		<dependency>
			<groupId>cz.cvut.kbss.jopa</groupId>
			<artifactId>jopa-impl</artifactId>
			<version>${jopa-version}</version>
		</dependency>
		<dependency>
			<groupId>cz.cvut.kbss.jopa</groupId>
			<artifactId>ontodriver-jena</artifactId> 
			<version>${jopa-version}</version>
			<exclusions>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	...

</project>
```

### 2. Compilation

**command:**

```shell
mvn clean compile aspectj:compile aspectj:test-compile -X
```

**output:**

```
...
[DEBUG] compiling C:\Users\piegsaj\git\transfer\src\test\java\learning\jopa\ExampleEntity.java
[INFO] Mixing interface 'cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable' (BeanListenerAspect.java) into type 'learning.jopa.ExampleEntity' (ExampleEntity.java)
[INFO] Type 'learning.jopa.ExampleEntity' (ExampleEntity.java) has intertyped method from 'cz.cvut.kbss.jopa.model.BeanListenerAspect' (BeanListenerAspect.java:'void cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable.setPersistenceContext(cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl)')
[INFO] Type 'learning.jopa.ExampleEntity' (ExampleEntity.java) has intertyped method from 'cz.cvut.kbss.jopa.model.BeanListenerAspect' (BeanListenerAspect.java:'cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable.getPersistenceContext()')
[INFO] Join point 'field-get(java.lang.String learning.jopa.ExampleEntity.issueType)' in Type 'learning.jopa.ExampleEntity' (ExampleEntity.java:30) advised by before advice from 'cz.cvut.kbss.jopa.model.BeanListenerAspect' (jopa-impl-1.1.1.jar!BeanListenerAspect.class(from BeanListenerAspect.java))
[DEBUG] woven class learning.jopa.ExampleEntity (from C:\Users\piegsaj\git\transfer\src\test\java\learning\jopa\ExampleEntity.java)

...

[WARNING] advice defined in cz.cvut.kbss.jopa.model.BeanListenerAspect has not been applied [Xlint:adviceDidNotMatch]
	C:\Users\piegsaj\.m2\repository\cz\cvut\kbss\jopa\jopa-impl\1.1.1\jopa-impl-1.1.1.jar!cz\cvut\kbss\jopa\model\BeanListenerAspect.class:0
```

### 3. Code execution

**command:**

```shell
mvn test -Dtest=learning.jopa.JopaLT
```

**output:**

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.701 s <<< FAILURE! - in learning.jopa.JopaLT
[ERROR] learning.jopa.JopaLT.test  Time elapsed: 10.683 s  <<< ERROR!
java.lang.ClassCastException: class learning.jopa.ExampleEntity cannot be cast to class cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable (learning.jopa.ExampleEntity and cz.cvut.kbss.jopa.model.BeanListenerAspect$Manageable are in unnamed module of loader 'app')
        at cz.cvut.kbss.jopa.model.BeanListenerAspect.deregister(BeanListenerAspect.java:99)
        at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.deregisterEntityFromPersistenceContext(UnitOfWorkImpl.java:669)
        at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.lambda$detachAllManagedInstances$1(UnitOfWorkImpl.java:272)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.detachAllManagedInstances(UnitOfWorkImpl.java:270)
        at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.clear(UnitOfWorkImpl.java:253)
        at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.release(UnitOfWorkImpl.java:720)
        at cz.cvut.kbss.jopa.model.EntityManagerImpl.removeCurrentPersistenceContext(EntityManagerImpl.java:597)
        at cz.cvut.kbss.jopa.model.EntityManagerImpl.close(EntityManagerImpl.java:404)
        at learning.jopa.JopaLT.test(JopaLT.java:51)
...
```

**Comment by ledsoft** [comment]
Hi Jens,
thanks for taking interest in JOPA! 
Correct me if I am wrong, but based on the logs you provided, the `ExampleEntity` is in test sources (`src/test/java`), isn't it? If it is so, the problem appears to be in the AspectJ Maven plugin configuration - JOPA entity classes in test sources are apparently not processed by it (despite what the first log says).
Could you confirm for me that the `ExampleEntity` is indeed in test sources? I managed to get the same exception as you with an entity class in test sources.
I will investigate why the configuration does not work as expected, as I see it is pretty much the same as in JOPA's examples repo.

**Comment by ledsoft** [comment]
Interestingly enough, if I just compile the code (using `mvn clean compile aspectj:compile aspectj:test-compile` as you did), it processes the entity class in test sources correctly (bytecode contains aspect join points). But if I run just `mvn test`, the class is not processed (bytecode does not contain aspect join points) when the tests are executed, leading to the aforementioned error.

**Comment by JensPiegsa** [comment]
Hello Martin,

Thank you for your prompt response.

Indeed, the `learning.jopa.ExampleEntity` class is located under `src/test/java`. By migrating it to `src/main/java`, I've managed to circumvent the problem. Thanks for pointing that out!

This just leaves the question of whether there is a proper Maven configuration that would permit placing an entity class within `/src/test/java` exclusively for testing? Let me know if you need any further information or if I can be of assistance.

Best,
Jens

**Comment by ledsoft** [comment]
Hi Jens,
I managed to find the problem. A separate `execution` must be declared for the AspectJ Maven plugin to process entity classes in test sources. With it, the tests run fine for me. Can you confirm it as well?

I also found that it is necessary to clean the project before running such tests. That is, I always use `mvn clean test` or `mvn clean package` to build the project. The AspectJ Maven plugin/compiler seems to have trouble processing already processed classes (or I am just unable to configure it correctly) - that is, if I run `mvn test` twice without cleaning the project, I get the exception again.

Anyway, I updated the [wiki](https://github.com/kbss-cvut/jopa/wiki/Maven-setup) and the [jopa-examples project](https://github.com/kbss-cvut/jopa-examples) to use the correct AspectJ Maven plugin configuration.
I am closing this issue, feel free to reopen it in case you have further trouble with configuring AspectJ for JOPA.

Cheers,
Martin
