### ISSUE TITLE
jopa-maven-plugin configuration validation error: pPackage required

### ISSUE THREAD

**Issue by JensPiegsa** [kbss-cvut/jopa#198]
Hi,

today I learned about `jopa-maven-plugin`, and I'm excited about its capabilities!

Here's a snippet of my configuration:

```xml
<plugin>
  <groupId>cz.cvut.kbss.jopa</groupId>
  <artifactId>jopa-maven-plugin</artifactId>
  <version>${jopa-version}</version>
  <configuration>
    <output-directory>${basedir}/src/main/java</output-directory>
    <package>rdf.entity</package>
    <ontology-iri>https://www.w3.org/ns/odrl/2/ODRL22.ttl</ontology-iri>
    <prefer-multilingual-strings>true</prefer-multilingual-strings>
  </configuration>
</plugin>
```

This is executable, however using the `<package>` tag, I get the validation error message:

> 'pPackage' child tag should be defined.

I think, this can be avoided, by using `@Parameter` `name` instead of `alias` in `cz.cvut.kbss.jopa.maven.OWL2JavaMojo`.

### Proposed change of `OWL2JavaMojo`:

_From:_

```
    private static final String PACKAGE_PARAM = "package";

    @Parameter(alias = PACKAGE_PARAM, required = true)
    private String pPackage;
```

_To:_

```
    private static final String PACKAGE_PARAM = "package";

    @Parameter(name = PACKAGE_PARAM, required = true)
    private String pPackage;
```

Additionally, the use of aliases seems to result in duplicate auto-complete suggestions in the IDE, which can be a bit confusing:

<img width="381" alt="pom xml" src="https://github.com/kbss-cvut/jopa/assets/6187787/97766176-a9fc-4f8f-b49d-12f8b4fb2d21">

**Comment by ledsoft** [comment]
Hi Jens, I changed the parameter mapping from `name` to `alias` in a recent release because I thought it better reflected the purpose, but apparently this confuses IDEs. I am reverting it back,as it makes no functional difference but works better with IDEs.
