### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by krietzsche** [kbss-cvut/jopa#214]
License file and GitHub state that JOPA is licensed under LGPL, but headers.txt (all headers in the source files) refer to GPL license. Please note that GPL and EPL (RDF4J license) aren't compatible https://www.eclipse.org/legal/eplfaq.php#GPLCOMPATIBLE

**Comment by ledsoft** [comment]
Hi,
thanks a lot for pointing that out! I have fixed it in development, it should be LGPL everywhere.
