### ISSUE TITLE
jopa-maven-plugin silently ignores imported ontologies that are invalid

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/jopa#22]
If I try to generate vocabulary by maven plugin (jopa-maven-plugin:0.9.12:owl2java-transform) for a configuration that has invalid imported ontologies, the plugin silently ignores them. (see relevant fragment of my configuration in the attachment). 

[configuration-to-reproduce-issue.zip](https://github.com/kbss-cvut/jopa/files/1560810/configuration-to-reproduce-issue.zip)

**Comment by ledsoft** [comment]
Fixed in 0.9.13.
