### ISSUE TITLE
Distinguishing string forms in the value sets of @Properties

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/jopa#27]
Problem
======
When @Properties are used they do not distinuguish between object IRIs, literals and their datatypes. For example. I have two OWL Classes:
@OWLClass(iri="http://example.org#A")
class A {
      @Properties
      private Map<String,Set<String>> props;
      @Types
      private Set<String> types;
}

@OWLClass(iri="http://example.org#B")
class B extends A {
      @OWLDataProperty(iri="http://example.org#p")
      private Integer p;
}

Then persisting a new instance of A, where the property is set through properties and the type B is set through types stores the property as a language-tagged literal. This makes the property unloadable into B through em.find(), because the type is Integer for B.

Proposal 1
========
Create a new Value class that serves for grouping IRIs and literals with datatypes/language tags

Proposal 2
========
Use a simple language in the values of the @Properties map. Each string would be either:

* ``'<'+IRI+'>'`` which would be interpreted as IRI and the property would be interpreted as an Object Property
* ``plainliteral`` whicch would be interpreted as a plain literal and equipped with the PU default language tag, i.e. ``plainliteral``@en
* ``'"'+lexform+'"^^'+datatypeIRI`` which would be interpreted as a datatyped literal.

**Comment by ledsoft** [comment]
Try using typed properties field. These should preserve the datatype when storing value.

E.g.

```java
...
@Properties
private Map<String, Set<Object>> properties;
...
```
