### ISSUE TITLE
Using an existing jena model

### ISSUE THREAD

**Issue by cristianolongoodhl** [kbss-cvut/jopa#270]
Hi, apologies if this is not the correct mean for my question. I'm using jopa with the jena ontodriver. Could I use an existing jena model with Jopa instead of the new one actually created by Jopa? If no, how can I get the underlying jena model?
thnx in advance.

**Comment by ledsoft** [comment]
Hi,
you cannot tell JOPA to load an existing model when initializing, but you can then replace the dataset it created (assuming it is an in-memory dataset) with another one. The code would be something like:

```java
import cz.cvut.kbss.ontodriver.jena.connector.ConnectorFactory;

EntityManager em = // init entity manager
Dataset toSet = // get existing dataset
em.unwrap(ConnectorFactory.class).setDataset(toSet);
```

Note that this will only work if the driver is configured to use an in-memory store (`cz.cvut.kbss.ontodriver.jena.storage=in-memory`).

**Comment by cristianolongoodhl** [comment]
Thank you very much
