### ISSUE TITLE
Use lists for plural fields populated by SPARQL queries by default

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/jopa#276]
SPARQL query mapped fields (fields annotated by `Sparql`) now uses a `Set` as targe type. However, the query result set is a list, so if the field type is `Collection`, the default selected implementation should be a `List`.

For example, in case of the following mapping:

```java
@Sparql(query = "SELECT ?x WHERE { ?x a <http://example.org/IsolationLevel> ; <http://example.org/hasIndex> ?index . } ORDER BY ?index")
Collection<IsolationLevel> isolationLevels;
```

the actual type of `isolationLevels` should be `List`.

**Comment by luxbe** [comment]
I think this is already possible with the current JOPA version

**Comment by ledsoft** [comment]
You are right. I have updated the issue description and title.
