### ISSUE TITLE
Non-deterministic Vocabulary generation

### ISSUE THREAD

**Issue by YanDoroshenko** [kbss-cvut/jopa#28]
When generating a Vocabulary from scripts that have the same prefix defined for different values, there's no way to predict which one will get what Vocabulary entry.

Discovered by @blcham.

**Comment by blcham** [comment]
In our case it happened that we had two prefixes imported from other ontologies indirectly. 
Ontology A (from which Vocabulary.java is generated)
Ontology B
Ontology C
A indirectly imports B,C. 
B contains prefix **dc**:"http://purl.org/dc/terms/description"
C contains prefix **dc**:"http://purl.org/dc/elements/1.1/description"


Resulting generated vocabulary was not deterministic :
{
  public final static String s_p_description = "http://purl.org/dc/terms/description";
  public final static String s_p_description_A = **"http://purl.org/dc/elements/1.1/description";**
   ....
}

or 

{
  public final static String s_p_description = "http://purl.org/dc/elements/1.1/description";
  public final static String s_p_description_A = **"http://purl.org/dc/terms/description";**
   ....
}

**Comment by ledsoft** [comment]
Fixed in 0.9.14.
