### ISSUE TITLE
NoSuchMethodError while executing jopa-maven-plugin:owl2java-transform

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/jopa#29]
jopa-maven-plugin:0.9.14:owl2java-transform fails within my project with error : 
`[ERROR] Failed to execute goal cz.cvut.kbss.jopa:jopa-maven-plugin:0.9.14:owl2java-transform (generate-sources) on project semantic-pipes-forms: Execution generate-sources of goal cz.cvut.kbss.jopa:jopa-maven-plugin:0.9.14:owl2java-transform failed: An API incompatibility was encountered while executing cz.cvut.kbss.jopa:jopa-maven-plugin:0.9.14:owl2java-transform: java.lang.NoSuchMethodError: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType`

It seems to me that the problem is in conflicting dependencies of the plugin:
```
~/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
~/.m2/repository/com/google/inject/guice/4.1.0/guice-4.1.0.jar
```

as both of them contain:
`./com/google/inject/util/Types.class`

[more-complete-error.log](https://github.com/kbss-cvut/jopa/files/1743563/error.log)

**Comment by ledsoft** [comment]
Fixed in 0.9.15.
