### ISSUE TITLE
ManagedSupperClass inherited by two entities cannot contain Id

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/jopa#3]
What does not work - JOPA complains about missing Id attribute for either B1 or B2:
@MappedSuperClass A0 {
@Id x;
}
@MappedSuperClass A extends A0{
}
@OWLClass B1 extends A{
}
@OWLClass B2 extends A {
}
=====
What works:

@MappedSuperClass A0 {
@Id x;
}
@MappedSuperClass A extends A0{
}
@OWLClass B1 extends A{
}

And respectively for B2

**Comment by ledsoft** [comment]
Unable to reproduce on 0.9.4.

**Comment by psiotwo** [comment]
Right, the bug was incorrectly described. The setup above is extended as follows:

@MappedSuperClass A0 {
@Id x;
}
@MappedSuperClass A extends A0{
    @OWLObjectProperty (..., cascade=CascadeType.ALL)
    Set<B1> set;
}
@OWLClass B1 extends A{
}
@OWLClass B2 extends A {
}

**Comment by ledsoft** [comment]
Fixed 0.9.5.
