### ISSUE TITLE
OWL2Java generates duplicate properties

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/jopa#30]
When OWL2Java processes an ontology with imports or different contexts and a property/class is encountered multiple times, multiple constants are generated for these occurrences into the vocabulary file.

It should skip properties/classes which were already added.

**Comment by blcham** [comment]
For me it generates from ontology [http://spinrdf.org/sp](http://spinrdf.org/sp)  Vocabulary.java file with the following fields:

```
    public final static String s_p_predicate = "http://spinrdf.org/sp#predicate";
    public final static String s_p_predicate_A = "http://spinrdf.org/sp#predicate";
```

The ontology does not have any imports and definition of property "predicate" is as follows:
```
sp:predicate a rdf:Property ;
        rdfs:subPropertyOf sp:systemProperty ;
        rdfs:range rdfs:Resource ;
        rdfs:label "predicate"^^xsd:string ;
        rdfs:domain sp:Triple ;
        rdfs:comment "A resource or Variable describing the predicate of a triple." .

```

**Comment by ledsoft** [comment]
Seems to be a probelm in OWLAPI. Opened an issue:
https://github.com/owlcs/owlapi/issues/736

Adding workaround which will eliminate duplicate properties from the generated vocabulary.

**Comment by ledsoft** [comment]
Closing the issue as the OWLAPI bug is still unresolved, but we have a workaround for it.
