### ISSUE TITLE
Allow using Lombok and JOPA in the same project

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/jopa#47]
Currently, a project cannot use JOPA and Lombok due to problems in the Maven build configuration (AspectJ maven plugin and Lombok).
Find a way to configure the build so that both libraries can be used in a project.

**Comment by psiotwo** [comment]
Maybe linked to https://github.com/rzwitserloot/lombok/issues/995

**Comment by ledsoft** [comment]
Example configuration described in [wiki](https://github.com/kbss-cvut/jopa/wiki/Using-Lombok) and demonstrated in https://github.com/kbss-cvut/jopa-examples/tree/master/example04-jopa-spring
