### ISSUE TITLE
Support mapping owl:oneOf to enums

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/jopa#60]
Currently, enums are mapped to plain data/annotation literals, so the information about the value being enumerated basically gets lost in the repository. At the same time, OWL already provides a mechanism of enumerating values - owl:oneOf. JOPA should support mapping to this.

**Comment by suryatejreddy** [comment]
I would like to work on this issue. Are there any specific guidelines to be followed before I start?

**Comment by ledsoft** [comment]
Hi, thanks for being interested in helping with development of JOPA.

There are unfortunately no guidelines for newcomers to the project. The idea for this feature is that there would be an annotation to map enum values to the ontological individuals. Another annotation would then be provided to use on entity attributes with enum-based values. Something like the JPA `@Enumerated`, but with an additional type - `ONE_OF`.

Try to work on the issue and feel free to ping me when you feel you have something worth sharing.
