### ISSUE TITLE
Class scanning issue

### ISSUE THREAD

**Issue by drexedam** [kbss-cvut/jopa#62]
Hi

I have an issue when generating a JAR from a Spring project.

# Issue
When building and running a JAR, scanning for classes only works if the packages are placed at the root of the JAR file. E.g., Spring places the project class files at _BOOT-INF/classes/_ and the files are not scanned at runtime leading to execptions like `java.lang.IllegalArgumentException: Class com.model.Example is not a known entity in this persistence unit.`.

## Details
The _[entryName](https://github.com/kbss-cvut/jopa/blob/85f025916f2e8fcbe1e952a30854e9cc83dc7ecb/jopa-impl/src/main/java/cz/cvut/kbss/jopa/loaders/ClasspathScanner.java#L102)_ in _[cz.cvut.kbss.jopa.loaders.ClasspathScanner#processJarFile](https://github.com/kbss-cvut/jopa/blob/85f025916f2e8fcbe1e952a30854e9cc83dc7ecb/jopa-impl/src/main/java/cz/cvut/kbss/jopa/loaders/ClasspathScanner.java#L92)_ is something like _BOOT-INF/classes/com/model/Example.class_ when running a Spring application as JAR.

Because only the beginning of the _entryName_ is [compared](https://github.com/kbss-cvut/jopa/blob/85f025916f2e8fcbe1e952a30854e9cc83dc7ecb/jopa-impl/src/main/java/cz/cvut/kbss/jopa/loaders/ClasspathScanner.java#L104) with _relPath_ (derived from the _packageName_ given to scan) no classes are added, though they exist in the JAR.

**Comment by ledsoft** [comment]
Hi, thanks a lot for the report and the detailed description!

Could you, please, try with version 0.13.5 (should be in Maven central in a couple of hours)?

**Comment by drexedam** [comment]
I tried 0.13.5 with my project and it seems to work.

Thanks for the quick fix.

**Comment by ledsoft** [comment]
Ok, cool. I'm closing the issue.
