### ISSUE TITLE
identifier and types fields are generated in subclasses too using owl2java

### ISSUE THREAD

**Issue by cristianolongo** [kbss-cvut/jopa#66]
if A subclass B, id, name, description, types and properties should be placed just in the generated java class corresponding to A , as the one corresponding to B extends the first one.

**Comment by cristianolongo** [comment]
see cz.cvut.kbss.jopa.owl2java.JavaTransformer.create

**Comment by ledsoft** [comment]
Thanks for the report and fix! Published in 0.14.2.
