### ISSUE TITLE
Add attribute ordering in to classes benerated by jopa maven plugin

### ISSUE THREAD

**Issue by cristianolongo** [kbss-cvut/jopa#69]
In orgder to alleviate Issue 2 of (https://github.com/kbss-cvut/jb4jsonld-jackson/issues/2)[jb4jsonld-jackson] provide a configuration parameter of the plugin to add the `@JsonLdAttributeOrder` annotation to all the OWLClasses generated by the plugin

**Comment by ledsoft** [comment]
Hi, thanks for the issue and the PR.
I'm a bit reluctant towards introducing a dependency on JB4JSON-LD into JOPA. I already created a follow-up issue [#17](https://github.com/kbss-cvut/jb4jsonld/issues/17). I'd rather solve this on the JB4JSON-LD side by introducing the deferred reference resolution. I haven't had much time to work on it recently, but with the beginning of the summer, I plan on looking into it.

Would that help with your case, or is there any other reason why being able to generate JSON-LD attribute ordering annotation in OWL2Java is needed?

**Comment by cristianolongo** [comment]
I'm just in troubles with serializing and deserializing jsonld. However I think that attribute ordering may be useful as it makes serialization result more predictable. May be a good idea to make it as default in jb4json-ld.

**Comment by ledsoft** [comment]
Ok, in that case, I would go with the deferred reference resolution in JB4JSON-LD. I agree with the default attribute ordering. There's a half-way attempt at it now - @id and @type are always output first during serialization but it makes sense to try to order the remaining attributes in some stable order (probably lexicographic).
It won't help with deserialization, as the spec says order of attributes does not matter and the jsonld-java library actually shuffles the incomming JSON-LD attributes during expansion. But at least the serialization output will be "nicer".

**Comment by cristianolongo** [comment]
However now it is clear to me that this relates to the jb4jsonld side, so i think this issue could be closed

**Comment by ledsoft** [comment]
Yeah, I was waiting for the issue to be done in JB4JSON-LD, but since I have finally started working on it, I think we can close this one and if it's ok with you, I'll close your PR without merging it.
