### ISSUE TITLE
Resilient repository connection

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/jopa#72]
To allow using JOPA in microservice setup, it should be more resilient towards RDF4J connection. In particular, OntoDriver should try reconnecting to the underlying data source. The reconnection strategy configuration (e.g. no. of attempts) should be configurable.

**Comment by ledsoft** [comment]
Changing title to repository, this applies to repository connections in general (at least those to an external sever, e.g. Fuseki).
