### ISSUE TITLE
JDK9 support

### ISSUE THREAD

**Issue by YanDoroshenko** [kbss-cvut/jopa#8]
JDK9 class loader is not a `java.net.URLClassLoader` anymore => `cz.cvut.kbss.jopa.loaders.EntityLoader.discoverEntities` fails with `ClassCastException`.

**Comment by ledsoft** [comment]
This is not the only issue with JDK 9 support.

We have to wait until AspectJ 1.9 is released, because the project is not buildable under the current version of AspectJ.

**Comment by ledsoft** [comment]
AspectJ 1.9 has been released. Now waiting for the new version of the aspect-maven-plugin, because 1.11 does not work (https://github.com/mojohaus/aspectj-maven-plugin/issues/24). After that, it should be possible to jump to Java 10.

**Comment by ledsoft** [comment]
Hi,
It's difficult to say, as we are waiting for the new aspectj maven plugin. They have the support for Java 9 mostly done (based on the issue referenced above), so hopefully they will release it soon.

**Comment by ledsoft** [comment]
So, the aspectj-maven-plugin still lags behind AspectJ's support for Java 9/10. Fortunately, as of JOPA **0.10.5**, it is possible to use Java 9/10 by switching from compile-time weaving to load-time weaving.

More info can be found on the [wiki](https://github.com/kbss-cvut/jopa/wiki/Maven-setup#aspectj), but basically one just needs to start the application with `javaagent` specifying path to aspectjweaver. The weaver will take care of weaving JOPA aspects into entity classes.

**Comment by ledsoft** [comment]
Since the official `aspect-maven-plugin` still doesn't have support for Java 9 and later, it is recommended to switch to a different fork of the plugin.

Documentation of how to do it together with a link to example projects using JOPA can be found on the [wiki](https://github.com/kbss-cvut/jopa/wiki/Maven-setup#java-9-and-beyond).
