### ISSUE TITLE
Support mapping any typed literal to String

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/jopa#96]
I would like to be able to load and **save** entities having a field referring to typed literal, but mapping it to String. Currently, I have following datatypes that I cannot have in data because JOPA does not support it:
```
xsd:time
xsd:date
csvw:uriTemplate
```
Here is an example of usage (see `datatypeIRI = CSVW.uriTemplate`):
```
class Column {
     @OWLDataProperty(iri = CSVW.propertyUrl, simpleLiteral = false, datatypeIRI = CSVW.uriTemplate)
     private String propertyUrl;
}
```

Of course next step would be to have custom Java classes to be mapped to custom datatypeIRI. As far as I know it is not possible now and thus this simple mapping would be sufficient for most of the cases. Otherwise user of JOPA is forced to change the data (remove custom datatypes) to be able to work with it properly. Or is there currently any workaround for that in JOPA ?

**Comment by ledsoft** [comment]
@blcham You can try the snapshot version 0.18.0-SNAPSHOT (published in Maven central). It has this feature implemented.

**Comment by blcham** [comment]
Thanks, we'll try it.
