### ISSUE TITLE
Relax participation constraint validation of inferred attributes on entity persist

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/jopa#98]
Consider an entity with the following setup

```java
@OWLClass(iri = "owl:Thing")
public class Thing {

    @Inferred
    @ParticipationConstraints(nonEmpty = "true")
    @OWLObjectProperty(iri = "ex:inferred")
    private Set<Thing> related;

    // Other stuff
}
```
If an instance of such an entity class is persisted, the operation will fail due to the constraint being violated. However, this is nonsensical, as the application cannot set a value of an inferred attribute, so there is no way to comply with the constraint. The constraint checking makes sense for inferred attributes only when an entity is loaded.

Therefore, participation constraint validation should not be performed for **inferred** attributes on entity persist.

**Comment by ledsoft** [comment]
FYI, @blcham , as per our discussion, feel free to provide additional details.

**Comment by blcham** [comment]
Just to be sure, i assume that you mean even that during "em.update()" will be cardinalities disabled for inferred filed

**Comment by blcham** [comment]
Of course based on the fact that reasoning is monotonic, you could assume some more fine-grained checks -- e.g. only min cardinalities would be checked in one case while only max cardinalities in another case ...
But this does not seem to be important at all right now for the cases we have.

**Comment by ledsoft** [comment]
I don't think there is a need to do the same for update as well. Since you are not able to edit the inferred attribute at all, the validation can be done, because it is expected, that it is validating a value already checked when the instance was loaded.
