### ISSUE TITLE
Enable bidirectional mapping of IRI-Java-types

### ISSUE THREAD

**Issue by twallmey** [kbss-cvut/jopa#99]
Jopa already offery access to a mapping of Java-Types to URIs via its MetaModel: entityManager.getMetaModel.entity(Test.class).getIRI()

It would be great to have an additional/inverted mapping to get Java-types by their IRIs: entityManager.getMetaModel.iri(TestIRI).getJavaType()

**Comment by ledsoft** [comment]
Implemented in development, scheduled for 0.18.0 release. Unfortunately, because multiple Java entity types can be mapped to the same class IRI, the metamodel method must return a set of entity types.
